spring:
  application:
    name: prepare-data

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5050/Input_Credit_Info
    username: root
    password: root
  default_schema: Client
  show_sql: true
  enable_lazy_load_no_trans: true

server:
  port: 8080
  sessionTimeout: 30